#!/usr/bin/env python3
"""
ibgateway — IBKR Gateway Lifecycle Manager
============================================
Replaces shell scripts for starting/stopping IB Gateway and QuestDB.
Also includes the keepalive-aware live tick streaming loop.

Usage (via run_ibkr.py):
    python run_ibkr.py --mode start
    python run_ibkr.py --mode stop
    python run_ibkr.py --mode stream
    python run_ibkr.py --mode status
"""

import os
import shutil
import signal
import socket
import subprocess
import sys
import textwrap
import time
from pathlib import Path
from typing import Dict, List, Optional

# ── paths ───────────────────────────────────────────────────────────────────

PROJECT_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = PROJECT_DIR / "scripts"
CONFIGS_DIR = PROJECT_DIR / "configs"
LOGS_DIR = PROJECT_DIR / "logs"
KEEPALIVE_FILE = PROJECT_DIR / ".ibkr_keepalive"
IBC_CONF_DIR = Path.home() / "Applications" / "IBC" / "conf"
IBC_PATH = str(Path.home() / "Applications" / "IBC")
TWS_MAJOR_VRSN = "10.45"
TWS_PATH = str(Path.home() / "Applications")
TWS_SETTINGS_PATH = str(Path.home() / "Jts")
QUESTDB_HOME = str(Path.home() / "apps" / "questdb-9.4.3")
JAVA_HOME_25 = "/usr/local/Cellar/openjdk@25/25.0.3"

IB_GW_PORT = 4002
IBC_CMD_PORT = 7462
QUESTDB_PORT = 9000


# ── credentials ─────────────────────────────────────────────────────────────

def get_credentials():
    """Read IB_USER, IB_PASS from environment. Source ~/.zshrc if needed."""
    user = os.environ.get("IB_USER")
    pw = os.environ.get("IB_PASS")
    if not user or not pw:
        zshrc = Path.home() / ".zshrc"
        if zshrc.exists():
            try:
                result = subprocess.run(
                    ["bash", "-c", f"source {zshrc} 2>/dev/null && echo \"${{IB_USER}}\" && echo \"${{IB_PASS}}\""],
                    capture_output=True, text=True, timeout=10
                )
                lines = result.stdout.strip().split("\n")
                if len(lines) >= 2 and lines[0] and lines[1]:
                    user, pw = lines[0], lines[1]
                    os.environ["IB_USER"] = user
                    os.environ["IB_PASS"] = pw
            except Exception:
                pass
    if not user or not pw:
        print("ERROR: IB_USER and IB_PASS must be set in environment",
              file=sys.stderr)
        print("Add to ~/.zshrc: export IB_USER='...' && export IB_PASS='...'",
              file=sys.stderr)
        sys.exit(1)
    return user, pw


# ── config.ini generation ───────────────────────────────────────────────────

def generate_config_ini(paper: bool = True):
    """Generate config.ini in IBC_CONF_DIR. Returns path to ini file."""
    IBC_CONF_DIR.mkdir(parents=True, exist_ok=True)
    user, pw = get_credentials()

    trading_mode = "paper" if paper else "live"

    ini_content = textwrap.dedent(f"""\
    # Auto-generated by ibgateway.py - DO NOT EDIT MANUALLY
    [IBC]
    FIX=no

    # Authentication
    IbLoginId={user}
    IbPassword={pw}

    # Trading Mode
    TradingMode={trading_mode}

    # Second Factor Authentication
    ReloginAfterSecondFactorAuthenticationTimeout=yes
    SecondFactorAuthenticationExitInterval=120
    SecondFactorAuthenticationTimeout=180

    # Startup
    MinimizeMainWindow=yes

    # Connection handling
    ExistingSessionDetectedAction=primary
    AcceptIncomingConnectionAction=accept
    AcceptNonBrokerageAccountWarning=yes
    ReadOnlyLogin=yes

    # API port
    OverrideTwsApiPort={IB_GW_PORT}

    # Closedown
    IbAutoClosedown=no
    AutoLogoffTime=
    AutoRestartTime=
    ClosedownAt=

    # Misc
    AllowBlindTrading=no

    # Command server
    CommandServerPort={IBC_CMD_PORT}
    ControlFrom=
    BindAddress=
    CommandPrompt=
    SuppressInfoMessages=yes

    # Diagnostics
    LogStructureWhen=open
    IncludeStackTraceForExceptions=no
    """)

    ini_path = IBC_CONF_DIR / "config.ini"
    ini_path.write_text(ini_content)
    print(f"Config written: {ini_path}")
    return ini_path


# ── QuestDB management ──────────────────────────────────────────────────────

def is_port_open(host: str, port: int, timeout: float = 2.0) -> bool:
    """Check if a TCP port is accepting connections."""
    try:
        s = socket.create_connection((host, port), timeout=timeout)
        s.close()
        return True
    except (OSError, socket.error):
        return False


def is_questdb_running() -> bool:
    """Check if QuestDB's HTTP port is open."""
    return is_port_open("127.0.0.1", QUESTDB_PORT, timeout=1.0)


def find_questdb_pid() -> Optional[int]:
    """Find QuestDB Java PID via pgrep."""
    try:
        result = subprocess.run(
            ["pgrep", "-f", "QuestDB-Runtime"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return int(result.stdout.strip().split()[0])
    except Exception:
        pass
    return None


def start_questdb():
    """Start QuestDB if not running. Uses JAVA_HOME_25."""
    if is_questdb_running():
        print("QuestDB is already running.")
        return

    questdb_sh = Path(QUESTDB_HOME) / "questdb.sh"
    if not questdb_sh.exists():
        print(f"ERROR: {questdb_sh} not found", file=sys.stderr)
        sys.exit(1)

    # Ensure Java 25 is used
    env = os.environ.copy()
    env["JAVA_HOME"] = JAVA_HOME_25

    print("Starting QuestDB...")
    subprocess.Popen(
        [str(questdb_sh), "start"],
        cwd=QUESTDB_HOME,
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    # Wait for it to come up
    for _ in range(30):
        if is_questdb_running():
            print("QuestDB started.")
            return
        time.sleep(1)

    print("WARNING: QuestDB did not become ready within 30s", file=sys.stderr)


def stop_questdb():
    """Stop QuestDB gracefully, force kill fallback."""
    questdb_sh = Path(QUESTDB_HOME) / "questdb.sh"
    if questdb_sh.exists():
        env = os.environ.copy()
        env["JAVA_HOME"] = JAVA_HOME_25
        subprocess.run(
            [str(questdb_sh), "stop"],
            cwd=QUESTDB_HOME, env=env,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            timeout=15,
        )

    # Force kill fallback
    pid = find_questdb_pid()
    if pid:
        print(f"Force killing QuestDB PID {pid}...")
        try:
            os.kill(pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        time.sleep(1)

    if is_questdb_running():
        print("WARNING: QuestDB still running after stop attempt",
              file=sys.stderr)
    else:
        print("QuestDB stopped.")

    # Clean PID files
    _clean_project_pid_files()


def _clean_project_pid_files():
    """Remove .ibkr_stream.pid and .ibkr_gateway.pid if they exist."""
    for name in (".ibkr_stream.pid", ".ibkr_gateway.pid"):
        f = PROJECT_DIR / name
        try:
            f.unlink()
        except FileNotFoundError:
            pass


# ── Gateway lifecycle ───────────────────────────────────────────────────────

def start_gateway():
    """Start IB Gateway via IBC. Blocks until Gateway process exits.

    1. Get credentials from env
    2. Generate config.ini
    3. Start QuestDB if needed
    4. Launch displaybannerandlaunch.sh --gateway as subprocess
    5. Block on subprocess (the Gateway runs until killed)
    """
    # Ensure scripts dir exists
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

    # Get credentials (validates env)
    user, pw = get_credentials()

    # Generate config for displaybannerandlaunch.sh
    ini_path = generate_config_ini(paper=True)

    # Start QuestDB
    start_questdb()

    # Ensure logs dir
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    # Locate displaybannerandlaunch.sh in project scripts
    display_script = SCRIPTS_DIR / "displaybannerandlaunch.sh"
    if not display_script.exists():
        print(f"ERROR: {display_script} not found. "
              "Run 'python3 -m ibgateway install_scripts' first.",
              file=sys.stderr)
        sys.exit(1)

    # Set up environment for displaybannerandlaunch.sh
    env = os.environ.copy()
    env.update({
        "TWS_MAJOR_VRSN": TWS_MAJOR_VRSN,
        "IBC_INI": str(ini_path),
        "TRADING_MODE": "paper",
        "TWOFA_TIMEOUT_ACTION": "exit",
        "IBC_PATH": IBC_PATH,          # ~/Applications/IBC
        "TWS_PATH": TWS_PATH,
        "TWS_SETTINGS_PATH": TWS_SETTINGS_PATH,
        "LOG_PATH": str(LOGS_DIR),
        "APP": "GATEWAY",
        "TWSUSERID": user,
        "TWSPASSWORD": pw,
        "JAVA_PATH": JAVA_HOME_25 + "/bin",
    })

    print("Starting IB Gateway...")
    print(f"  Display script: {display_script}")
    print(f"  Config: {ini_path}")

    # Launch as subprocess; it blocks until gateway exits
    proc = subprocess.Popen(
        ["/bin/bash", str(display_script)],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    # Write PID files so we can check later
    pid_file = LOGS_DIR / "gateway.pid"
    pid_file.write_text(str(proc.pid))
    # Also write canonical PID file for duplicate-instance guard
    gw_pid_file = PROJECT_DIR / ".ibkr_gateway.pid"
    gw_pid_file.write_text(str(os.getpid()) + "\n")

    print(f"Gateway subprocess started (PID {proc.pid}), waiting for exit...")
    try:
        proc.wait()
    finally:
        print("Gateway subprocess terminated.")
        if pid_file.exists():
            pid_file.unlink()
        # Clean canonical PID file
        try:
            gw_pid_file.unlink()
        except FileNotFoundError:
            pass


def wait_for_api(timeout: int = 120) -> bool:
    """Poll port 4002 via ib_insync until API is ready. Returns True if ready."""
    from ib_insync import IB
    deadline = time.time() + timeout
    attempt = 0

    while time.time() < deadline:
        attempt += 1
        ib = IB()
        try:
            ib.connect("127.0.0.1", IB_GW_PORT,
                       clientId=1, readonly=True, timeout=3)
            print(f"API ready on attempt {attempt}.")
            ib.disconnect()
            return True
        except Exception as e:
            if attempt == 1:
                print(f"Waiting for API (attempt {attempt})...", end="")
            elif attempt % 5 == 0:
                print(f" {attempt}", end="")
            else:
                print(".", end="")
            sys.stdout.flush()
            time.sleep(2)
        finally:
            try:
                ib.disconnect()
            except Exception:
                pass

    print()
    print(f"ERROR: API not ready after {timeout}s timeout", file=sys.stderr)
    return False


def stop_gateway():
    """Gracefully stop Gateway, kill fallback, then stop QuestDB.

    1. Send STOP to IBC via command port 7462
    2. Run scripts/commandsend.sh STOP if available
    3. Wait 5s, check if dead
    4. SIGTERM → SIGKILL fallback for leftover java processes
    5. Stop QuestDB
    """
    print("Stopping Gateway...")

    # Method 1: send STOP via netcat (nc) to IBC command port
    _send_stop_via_nc()

    # Method 2: use commandsend.sh if available
    cmd_send = SCRIPTS_DIR / "commandsend.sh"
    if cmd_send.exists():
        try:
            subprocess.run(
                [str(cmd_send), "STOP"],
                timeout=10,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as e:
            print(f"  commandsend.sh warning: {e}")

    # Wait for graceful shutdown
    time.sleep(5)

    # Find and kill remaining java gateway processes
    _kill_java_processes("ibgateway", "IBC")
    _kill_java_processes("IBC")

    # Stop QuestDB
    stop_questdb()

    # Clean keepalive
    set_keepalive(False)
    print("Gateway and services stopped.")


def _send_stop_via_nc():
    """Send STOP command to IBC command server via netcat."""
    try:
        s = socket.create_connection(("127.0.0.1", IBC_CMD_PORT), timeout=3)
        s.sendall(b"STOP\r\n")
        time.sleep(0.5)
        s.sendall(b"EXIT\r\n")
        s.close()
        print("  STOP sent via socket.")
    except Exception as e:
        print(f"  Socket STOP failed (normal if Gateway not running): {e}")


def _kill_java_processes(*patterns: str):
    """Kill Java processes matching any of the given patterns."""
    for pat in patterns:
        try:
            result = subprocess.run(
                ["pgrep", "-f", pat],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode != 0:
                continue
            pids = [int(p) for p in result.stdout.strip().split()]
            for pid in pids:
                print(f"  Sending SIGTERM to PID {pid} ({pat})...")
                try:
                    os.kill(pid, signal.SIGTERM)
                except ProcessLookupError:
                    pass
        except Exception:
            pass

    # Wait 3s then SIGKILL remaining
    time.sleep(3)
    for pat in patterns:
        try:
            result = subprocess.run(
                ["pgrep", "-f", pat],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode != 0:
                continue
            pids = [int(p) for p in result.stdout.strip().split()]
            for pid in pids:
                print(f"  Sending SIGKILL to PID {pid} ({pat})...")
                try:
                    os.kill(pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
        except Exception:
            pass


# ── Status ──────────────────────────────────────────────────────────────────

def gateway_status() -> Dict:
    """Return dict with status of all components."""
    status = {
        "questdb": {"running": False, "port": QUESTDB_PORT, "pid": None},
        "gateway": {"running": False, "port": IB_GW_PORT, "pid": None},
        "keepalive": False,
    }

    # QuestDB
    qpid = find_questdb_pid()
    if qpid:
        status["questdb"]["running"] = True
        status["questdb"]["pid"] = qpid

    # Gateway - check port
    status["gateway"]["running"] = is_port_open("127.0.0.1", IB_GW_PORT, timeout=1.0)

    # Gateway PID - look for displaybannerandlaunch or ibcstart
    try:
        result = subprocess.run(
            ["pgrep", "-f", "displaybannerandlaunch"],
            capture_output=True, text=True, timeout=3,
        )
        if result.returncode == 0 and result.stdout.strip():
            status["gateway"]["pid"] = int(result.stdout.strip().split()[0])
    except Exception:
        pass

    # Keepalive
    status["keepalive"] = is_keepalive_enabled()

    return status


# ── Keepalive ───────────────────────────────────────────────────────────────

def is_keepalive_enabled() -> bool:
    """Check if KEEPALIVE_FILE exists and contains 'true'."""
    if not KEEPALIVE_FILE.exists():
        return False
    return KEEPALIVE_FILE.read_text().strip().lower() == "true"


def set_keepalive(val: bool):
    """Write 'true' or 'false' to KEEPALIVE_FILE."""
    content = "true" if val else "false"
    KEEPALIVE_FILE.write_text(content + "\n")
    print(f"Keepalive set to {content}")


# ── Ensure gateway is ready ─────────────────────────────────────────────────

def ensure_gateway(timeout: int = 120) -> bool:
    """Idempotent: if API ready → return True; if dead → start; if running but API gone → restart."""
    if is_port_open("127.0.0.1", IB_GW_PORT, timeout=1.0):
        # Quick check with ib_insync
        from ib_insync import IB
        ib = IB()
        try:
            ib.connect("127.0.0.1", IB_GW_PORT, clientId=1,
                       readonly=True, timeout=3)
            ib.disconnect()
            return True
        except Exception:
            print("Gateway port open but API not responding; restarting...")
            stop_gateway()
            time.sleep(3)
        finally:
            try:
                ib.disconnect()
            except Exception:
                pass

    # Start gateway in background thread
    import threading
    gw_thread = threading.Thread(target=start_gateway, daemon=True)
    gw_thread.start()

    if wait_for_api(timeout=timeout):
        print("Gateway is ready.")
        return True
    else:
        print("ERROR: Gateway failed to become ready", file=sys.stderr)
        return False


# ── Tick config loading ─────────────────────────────────────────────────────

def load_tick_config() -> list:
    """Load and validate configs/download_live_tick.json. Return list of contract dicts.

    Validation rules:
    - File must exist → sys.exit(1) with "ERROR: configs/download_live_tick.json not found"
    - Must be valid JSON → sys.exit(1) with "ERROR: ... is not valid JSON: <error>"
    - Must have "contracts" key with non-empty list → sys.exit(1) with "ERROR: ... must contain a non-empty 'contracts' list"
    - Each contract must have "ric" (non-empty string) → sys.exit(1) with "ERROR: each contract must have a 'ric' field"
    - "duration_seconds" defaults to 0 if missing
    """
    import json

    config_path = CONFIGS_DIR / "download_live_tick.json"
    if not config_path.exists():
        print(f"ERROR: {config_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        data = json.loads(config_path.read_text())
    except json.JSONDecodeError as e:
        print(f"ERROR: {config_path} is not valid JSON: {e}", file=sys.stderr)
        sys.exit(1)

    if "contracts" not in data or not isinstance(data["contracts"], list) or not data["contracts"]:
        print(f"ERROR: {config_path} must contain a non-empty 'contracts' list",
              file=sys.stderr)
        sys.exit(1)

    validated = []
    for i, c in enumerate(data["contracts"]):
        if not isinstance(c, dict) or "ric" not in c or not isinstance(c["ric"], str) or not c["ric"].strip():
            print(f"ERROR: each contract must have a 'ric' field (contract index {i})",
                  file=sys.stderr)
            sys.exit(1)
        validated.append({
            "ric": c["ric"].strip(),
            "duration_seconds": c.get("duration_seconds", 0),
        })

    return validated


# ── Keepalive-aware tick streaming loop ─────────────────────────────────────

def stream_ticks_loop():
    """Main keepalive-aware loop.

    1. Check keepalive → if disabled, print and exit 0
    2. Load tick config (exits with error if invalid)
    3. Loop:
       a. Check keepalive → if disabled, exit 0
       b. ensure_gateway()
       c. Import and call download_ticks._stream_live_ticks-like logic
       d. If tick stream ends (Gateway died), sleep 5s and loop back
    4. On any fatal error, set keepalive=false, print error, exit with code 1
    """
    if not is_keepalive_enabled():
        print("Keepalive is disabled; stream_ticks_loop exiting.")
        sys.exit(0)

    contracts = load_tick_config()
    print(f"Loaded {len(contracts)} contract(s) from config.")

    while is_keepalive_enabled():
        if not ensure_gateway():
            print("Gateway unavailable; will retry in 5s.",
                  file=sys.stderr)
            time.sleep(5)
            continue

        from ib_insync import IB, util
        from ibkr_utils import build_ric_contract

        ib = IB()
        try:
            ib.connect("127.0.0.1", IB_GW_PORT, clientId=2,
                       readonly=True, timeout=10)
            print("Connected for streaming.")

            # Resolve all contracts
            resolved_contracts = []
            for c in contracts:
                ric = c["ric"]
                contract = build_ric_contract(ric)
                print(f"Resolving {ric}...")
                details = ib.reqContractDetails(contract)
                if not details:
                    print(f"WARNING: Could not resolve {ric}, skipping",
                          file=sys.stderr)
                    continue
                cd = details[0]
                resolved = cd.contract
                ric_label = resolved.localSymbol or ric.upper()
                expiry = ""
                ltd = getattr(resolved, 'lastTradeDateOrContractMonth', '')
                if ltd:
                    if len(ltd) == 8:
                        expiry = f"{ltd[0:4]}-{ltd[4:6]}-{ltd[6:8]}"
                    elif len(ltd) == 6:
                        expiry = f"{ltd[0:4]}-{ltd[4:6]}-01"
                if not expiry:
                    re = getattr(cd, 'realExpirationDate', '')
                    if re:
                        expiry = f"{re[0:4]}-{re[4:6]}-{re[6:8]}" if len(re) == 8 else re
                resolved_contracts.append((resolved, ric_label, expiry))
                print(f"  Resolved: {ric_label} (expiry: {expiry})")

            if not resolved_contracts:
                print("No contracts could be resolved; sleeping 10s...",
                      file=sys.stderr)
                time.sleep(10)
                continue

            # Determine max duration for the stream call
            durations = [c["duration_seconds"] for c in contracts
                         if any(r[1] == load_tick_config()[i]["ric"]
                                or load_tick_config()[i]["ric"] == c["ric"]
                                for i, r in enumerate(resolved_contracts))]
            # Use the max duration (0 = forever)
            max_duration = max(durations) if durations else 0

            # Import and call the streaming function
            from download_ticks import _stream_live_ticks
            _stream_live_ticks(
                ib, resolved_contracts,
                max_duration,
                f"http://127.0.0.1:{QUESTDB_PORT}",
            )

            # If duration-based, check keepalive and loop
            if max_duration > 0:
                print("Duration-based stream completed; rechecking keepalive...")
                continue

            # If _stream_live_ticks returned (Ctrl+C or error), check keepalive
            if not is_keepalive_enabled():
                print("Keepalive disabled during stream.")
                break

        except Exception as e:
            print(f"ERROR in stream: {e}", file=sys.stderr)
            if not is_keepalive_enabled():
                break
            print("Will retry in 5s...")
            time.sleep(5)
        finally:
            try:
                ib.disconnect()
            except Exception:
                pass

    if not is_keepalive_enabled():
        print("Stream exiting: keepalive disabled.")
        sys.exit(0)


# ── Script installation ─────────────────────────────────────────────────────

def install_scripts():
    """Copy IBC scripts from ~/Applications/IBC into project scripts/ dir."""
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

    mappings = [
        ("displaybannerandlaunch.sh", "scripts/displaybannerandlaunch.sh"),
        ("ibcstart.sh", "scripts/ibcstart.sh"),
        ("stop.sh", "scripts/stop.sh"),
        ("commandsend.sh", "scripts/commandsend.sh"),
        ("version", "scripts/version"),
    ]

    ibc_root = Path.home() / "Applications" / "IBC"

    for src_name, dest_rel in mappings:
        src = ibc_root / src_name
        if src_name == "scripts/displaybannerandlaunch.sh":
            src = ibc_root / "scripts" / "displaybannerandlaunch.sh"
        elif src_name == "scripts/ibcstart.sh":
            src = ibc_root / "scripts" / "ibcstart.sh"
        dest = PROJECT_DIR / dest_rel

        if src.exists():
            shutil.copy2(str(src), str(dest))
            dest.chmod(dest.stat().st_mode | 0o111)  # +x
            print(f"  Copied {src} → {dest}")
        else:
            print(f"  WARNING: {src} not found, skipping", file=sys.stderr)
            # Create empty placeholder with +x
            dest.write_text("#!/bin/bash\necho 'Placeholder: install real script at " + str(src) + "'\n")
            dest.chmod(0o755)

    print("Scripts installed.")
