#!/usr/bin/env python3
"""
ibgateway — IBKR Gateway Lifecycle Manager
===================================================
Manages IB Gateway start/stop/status, credentials, config generation,
and script installation.

Usage (via run_service.py or session_manager.py):
    python run_service.py --mode start
    python run_service.py --mode stop
    python run_service.py --mode status
"""

import os
import secrets
import shutil
import signal
import socket
import subprocess
import sys
import textwrap
import threading
import time
from pathlib import Path
from typing import Callable, Dict, List, Optional

from ib_insync import IB
from questdb import QuestDBManager
from logger import get_logger

logger = get_logger(__name__)


# ── paths ───────────────────────────────────────────────────────────────────

PROJECT_DIR = Path(__file__).resolve().parent
CONFIGS_DIR = PROJECT_DIR / "configs"
SCRIPTS_DIR = PROJECT_DIR / "scripts"
LOGS_DIR = PROJECT_DIR / "logs"
IBC_CONF_DIR = Path.home() / "Applications" / "IBC" / "conf"
IBC_PATH = str(Path.home() / "Applications" / "IBC")
TWS_MAJOR_VRSN = "10.45"
TWS_PATH = str(Path.home() / "Applications")
TWS_SETTINGS_PATH = str(Path.home() / "Jts")
JAVA_HOME_25 = "/usr/local/Cellar/openjdk@25/25.0.3"

IB_GW_PORT = 4002
IBC_CMD_PORT = 7462
QUESTDB_PORT = 9000


# ── credentials ─────────────────────────────────────────────────────────────

##
# Read IB_USER and IB_PASS from environment, falling back to ~/.zshrc.
#
# @return: A (user, password) tuple of strings.
# @raise SystemExit: If neither environment variable is set.
def get_credentials() -> tuple:
    user = os.environ.get("IB_USER")
    pw = os.environ.get("IB_PASS")
    if not user or not pw:
        zshrc = Path.home() / ".zshrc"
        if zshrc.exists():
            try:
                result = subprocess.run(
                    ["bash", "-c", f"source {zshrc} 2>/dev/null && echo \"${{IB_USER}}\" && echo \"${{IB_PASS}}\""],
                    capture_output=True, text=True, timeout=10
                )
                lines = result.stdout.strip().split("\n")
                if len(lines) >= 2 and lines[0] and lines[1]:
                    user, pw = lines[0], lines[1]
                    os.environ["IB_USER"] = user
                    os.environ["IB_PASS"] = pw
            except Exception:
                pass
    if not user or not pw:
        logger.error("IB_USER and IB_PASS must be set in environment")
        logger.error("Add to ~/.zshrc: export IB_USER='...' && export IB_PASS='...'")
        sys.exit(1)
    return user, pw


# ── config.ini generation ───────────────────────────────────────────────────

##
# Generate config.ini in the IBC config directory.
#
# @param paper: If True, write TradingMode=paper; otherwise live.
# @return: Path to the generated config.ini file.
def generate_config_ini(paper: bool = True) -> Path:
    IBC_CONF_DIR.mkdir(parents=True, exist_ok=True)
    user, pw = get_credentials()

    trading_mode = "paper" if paper else "live"

    ini_content = textwrap.dedent(f"""\
    # Auto-generated by ibgateway.py - DO NOT EDIT MANUALLY
    [IBC]
    FIX=no

    # Authentication
    IbLoginId={user}
    IbPassword={pw}

    # Trading Mode
    TradingMode={trading_mode}

    # Second Factor Authentication
    ReloginAfterSecondFactorAuthenticationTimeout=yes
    SecondFactorAuthenticationExitInterval=120
    SecondFactorAuthenticationTimeout=180

    # Startup
    MinimizeMainWindow=yes

    # Connection handling
    ExistingSessionDetectedAction=primary
    AcceptIncomingConnectionAction=accept
    AcceptNonBrokerageAccountWarning=yes
    ReadOnlyLogin=yes

    # API port
    OverrideTwsApiPort={IB_GW_PORT}

    # Closedown
    IbAutoClosedown=no
    AutoLogoffTime=
    AutoRestartTime=
    ClosedownAt=

    # Misc
    AllowBlindTrading=no

    # Command server
    CommandServerPort={IBC_CMD_PORT}
    ControlFrom=
    BindAddress=
    CommandPrompt=
    SuppressInfoMessages=yes

    # Diagnostics
    LogStructureWhen=open
    IncludeStackTraceForExceptions=no
    """)

    ini_path = IBC_CONF_DIR / "config.ini"
    ini_path.write_text(ini_content)
    logger.info("Config written: %s", ini_path)
    return ini_path


# ── Gateway lifecycle ───────────────────────────────────────────────────────

class IBGateway:
    """Object-oriented lifecycle manager for the IBKR Gateway."""

    def __init__(self, on_gateway_terminated: Optional[List[Callable[[int], None]]] = None):
        self.project_dir = PROJECT_DIR
        self.configs_dir = CONFIGS_DIR
        self.scripts_dir = SCRIPTS_DIR
        self.logs_dir = LOGS_DIR
        self.ibc_conf_dir = IBC_CONF_DIR
        self.ibc_path = IBC_PATH
        self.tws_major_vrsn = TWS_MAJOR_VRSN
        self.tws_path = TWS_PATH
        self.tws_settings_path = TWS_SETTINGS_PATH
        self.java_home_25 = JAVA_HOME_25
        self.on_gateway_terminated = on_gateway_terminated or []

    def add_gateway_terminated_handler(self, handler: Callable[[int], None]) -> None:
        self.on_gateway_terminated.append(handler)

    @staticmethod
    def get_credentials() -> tuple:
        user = os.environ.get("IB_USER")
        pw = os.environ.get("IB_PASS")
        if not user or not pw:
            zshrc = Path.home() / ".zshrc"
            if zshrc.exists():
                try:
                    result = subprocess.run(
                        ["bash", "-c", f"source {zshrc} 2>/dev/null && echo \"${{IB_USER}}\" && echo \"${{IB_PASS}}\""],
                        capture_output=True, text=True, timeout=10,
                    )
                    lines = result.stdout.strip().split("\n")
                    if len(lines) >= 2 and lines[0] and lines[1]:
                        user, pw = lines[0], lines[1]
                        os.environ["IB_USER"] = user
                        os.environ["IB_PASS"] = pw
                except Exception:
                    pass
        if not user or not pw:
            logger.error("IB_USER and IB_PASS must be set in environment")
            logger.error("Add to ~/.zshrc: export IB_USER='...' && export IB_PASS='...'")
            sys.exit(1)
        return user, pw

    def generate_config_ini(self, paper: bool = True) -> Path:
        self.ibc_conf_dir.mkdir(parents=True, exist_ok=True)
        user, pw = self.get_credentials()

        trading_mode = "paper" if paper else "live"

        ini_content = textwrap.dedent(f"""\
        # Auto-generated by ibgateway.py - DO NOT EDIT MANUALLY
        [IBC]
        FIX=no

        # Authentication
        IbLoginId={user}
        IbPassword={pw}

        # Trading Mode
        TradingMode={trading_mode}

        # Second Factor Authentication
        ReloginAfterSecondFactorAuthenticationTimeout=yes
        SecondFactorAuthenticationExitInterval=120
        SecondFactorAuthenticationTimeout=180

        # Startup
        MinimizeMainWindow=yes

        # Connection handling
        ExistingSessionDetectedAction=primary
        AcceptIncomingConnectionAction=accept
        AcceptNonBrokerageAccountWarning=yes
        ReadOnlyLogin=yes

        # API port
        OverrideTwsApiPort={IB_GW_PORT}

        # Closedown
        IbAutoClosedown=no
        AutoLogoffTime=
        AutoRestartTime=
        ClosedownAt=

        # Misc
        AllowBlindTrading=no

        # Command server
        CommandServerPort={IBC_CMD_PORT}
        ControlFrom=
        BindAddress=
        CommandPrompt=
        SuppressInfoMessages=yes

        # Diagnostics
        LogStructureWhen=open
        IncludeStackTraceForExceptions=no
        """)

        ini_path = self.ibc_conf_dir / "config.ini"
        ini_path.write_text(ini_content)
        logger.info("Config written: %s", ini_path)
        return ini_path

    def start_gateway(self):
        self.scripts_dir.mkdir(parents=True, exist_ok=True)

        user, pw = self.get_credentials()
        ini_path = self.generate_config_ini(paper=True)

        self.logs_dir.mkdir(parents=True, exist_ok=True)

        display_script = self.scripts_dir / "displaybannerandlaunch.sh"
        if not display_script.exists():
            logger.error("%s not found. Run 'python3 -m ibgateway install_scripts' first.",
                         display_script)
            sys.exit(1)

        env = os.environ.copy()
        env.update({
            "TWS_MAJOR_VRSN": self.tws_major_vrsn,
            "IBC_INI": str(ini_path),
            "TRADING_MODE": "paper",
            "TWOFA_TIMEOUT_ACTION": "exit",
            "IBC_PATH": self.ibc_path,
            "TWS_PATH": self.tws_path,
            "TWS_SETTINGS_PATH": self.tws_settings_path,
            "LOG_PATH": str(self.logs_dir),
            "APP": "GATEWAY",
            "TWSUSERID": user,
            "TWSPASSWORD": pw,
            "JAVA_PATH": self.java_home_25 + "/bin",
        })

        def _run_gateway():
            proc = subprocess.Popen(
                ["/bin/bash", str(display_script)],
                env=env,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )

            logger.info("Gateway subprocess started (PID %d)...", proc.pid)
            try:
                proc.wait()
            finally:
                logger.info("Gateway subprocess terminated.")
                for handler in self.on_gateway_terminated:
                    try:
                        handler(proc.pid)
                    except Exception:
                        logger.exception("Error in gateway termination callback")

        t = threading.Thread(target=_run_gateway, daemon=True)
        t.start()
        return t

    def wait_for_api(self, mgr, timeout: int = 120) -> bool:
        deadline = time.time() + timeout
        attempt = 0

        while time.time() < deadline:
            attempt += 1

            status = self._probe_gateway_api(timeout=min(5, max(1, timeout // 10)))
            if status:
                logger.info("Gateway API is reachable on attempt %d.", attempt)
                return True
                        
            if attempt == 1:
                logger.info("Waiting for API (attempt %d)...", attempt)
            time.sleep(2)

        logger.error("API not ready after %ds timeout", timeout)
        return False

    def stop_gateway(self):
        logger.info("Stopping Gateway...")

        self._send_stop_via_nc()

        cmd_send = self.scripts_dir / "commandsend.sh"
        if cmd_send.exists():
            try:
                subprocess.run(
                    [str(cmd_send), "STOP"],
                    timeout=10,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            except Exception as e:
                logger.warning("commandsend.sh warning: %s", e)

        time.sleep(5)

        self._kill_java_processes("ibgateway", "IBC")
        self._kill_java_processes("IBC")

        logger.info("Gateway and services stopped.")

    def _send_stop_via_nc(self):
        try:
            s = socket.create_connection(("127.0.0.1", IBC_CMD_PORT), timeout=3)
            s.sendall(b"STOP\r\n")
            time.sleep(0.5)
            s.sendall(b"EXIT\r\n")
            s.close()
            logger.info("  STOP sent via socket.")
        except Exception as e:
            logger.info("  Socket STOP failed (normal if Gateway not running): %s", e)

    def _kill_java_processes(self, *patterns: str):
        for pat in patterns:
            try:
                result = subprocess.run(
                    ["pgrep", "-f", pat],
                    capture_output=True, text=True, timeout=5,
                )
                if result.returncode != 0:
                    continue
                pids = [int(p) for p in result.stdout.strip().split()]
                for pid in pids:
                    logger.info("  Sending SIGTERM to PID %d (%s)...", pid, pat)
                    try:
                        os.kill(pid, signal.SIGTERM)
                    except ProcessLookupError:
                        pass
            except Exception:
                pass

        time.sleep(3)
        for pat in patterns:
            try:
                result = subprocess.run(
                    ["pgrep", "-f", pat],
                    capture_output=True, text=True, timeout=5,
                )
                if result.returncode != 0:
                    continue
                pids = [int(p) for p in result.stdout.strip().split()]
                for pid in pids:
                    logger.info("  Sending SIGKILL to PID %d (%s)...", pid, pat)
                    try:
                        os.kill(pid, signal.SIGKILL)
                    except ProcessLookupError:
                        pass
            except Exception:
                pass

    def _probe_gateway_api(self, timeout: int = 5) -> bool:
        try:
            ib = IB()
            try:
                ib.connect(
                    "127.0.0.1",
                    IB_GW_PORT,
                    clientId=secrets.randbelow(900) + 100,
                    readonly=True,
                    timeout=timeout,
                )
                return True
            finally:
                try:
                    ib.disconnect()
                except Exception:
                    pass
        except Exception:
            logger.debug("Gateway API probe failed", exc_info=True)
            return False

    def ensure_gateway(self, mgr, timeout: int = 120) -> bool:
        if self._probe_gateway_api(timeout=min(5, max(1, timeout // 10))):
            logger.info("Gateway API is already reachable.")
            return True

        if QuestDBManager.is_port_open("127.0.0.1", IB_GW_PORT, timeout=1.0):
            logger.info("Gateway port is open but API probe failed; restarting once.")
            self.stop_gateway()
            time.sleep(3)

        gw_thread = threading.Thread(target=self.start_gateway, daemon=True)
        gw_thread.start()

        if self.wait_for_api(mgr, timeout=timeout):
            logger.info("Gateway is ready.")
            return True
        logger.error("Gateway failed to become ready")
        return False

# ── Script installation ─────────────────────────────────────────────────────

##
# Copy IBC scripts from ~/Applications/IBC into the project scripts directory.
#
# Creates executable copies of displaybannerandlaunch.sh, ibcstart.sh, stop.sh,
# commandsend.sh, and version.  Missing source scripts are replaced with stub
# placeholders.
def install_scripts():
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

    mappings = [
        ("displaybannerandlaunch.sh", "scripts/displaybannerandlaunch.sh"),
        ("ibcstart.sh", "scripts/ibcstart.sh"),
        ("stop.sh", "scripts/stop.sh"),
        ("commandsend.sh", "scripts/commandsend.sh"),
        ("version", "scripts/version"),
    ]

    ibc_root = Path.home() / "Applications" / "IBC"

    for src_name, dest_rel in mappings:
        src = ibc_root / src_name
        if src_name == "scripts/displaybannerandlaunch.sh":
            src = ibc_root / "scripts" / "displaybannerandlaunch.sh"
        elif src_name == "scripts/ibcstart.sh":
            src = ibc_root / "scripts" / "ibcstart.sh"
        dest = PROJECT_DIR / dest_rel

        if src.exists():
            shutil.copy2(str(src), str(dest))
            dest.chmod(dest.stat().st_mode | 0o111)
            logger.info("  Copied %s -> %s", src, dest)
        else:
            logger.warning("  %s not found, skipping", src)
            dest.write_text("#!/bin/bash\necho 'Placeholder: install real script at " + str(src) + "'\n")
            dest.chmod(0o755)

    logger.info("Scripts installed.")
