#!/usr/bin/env python3
"""
ibgateway — IBKR Gateway Lifecycle Manager
===================================================
Manages IB Gateway start/stop/status, credentials, config generation,
and script installation.

Usage (via run_service.py or session_manager.py):
    python run_service.py --mode start
    python run_service.py --mode stop
    python run_service.py --mode status
"""

import os
import shutil
import signal
import socket
import subprocess
import sys
import textwrap
import time
from pathlib import Path
from typing import Dict, Optional

from questdb import QuestDBManager
from logger import get_logger

logger = get_logger(__name__)


# ── paths ───────────────────────────────────────────────────────────────────

PROJECT_DIR = Path(__file__).resolve().parent
CONFIGS_DIR = PROJECT_DIR / "configs"
SCRIPTS_DIR = PROJECT_DIR / "scripts"
LOGS_DIR = PROJECT_DIR / "logs"
IBC_CONF_DIR = Path.home() / "Applications" / "IBC" / "conf"
IBC_PATH = str(Path.home() / "Applications" / "IBC")
TWS_MAJOR_VRSN = "10.45"
TWS_PATH = str(Path.home() / "Applications")
TWS_SETTINGS_PATH = str(Path.home() / "Jts")
JAVA_HOME_25 = "/usr/local/Cellar/openjdk@25/25.0.3"

IB_GW_PORT = 4002
IBC_CMD_PORT = 7462
QUESTDB_PORT = 9000


# ── credentials ─────────────────────────────────────────────────────────────

##
# Read IB_USER and IB_PASS from environment, falling back to ~/.zshrc.
#
# @return: A (user, password) tuple of strings.
# @raise SystemExit: If neither environment variable is set.
def get_credentials() -> tuple:
    user = os.environ.get("IB_USER")
    pw = os.environ.get("IB_PASS")
    if not user or not pw:
        zshrc = Path.home() / ".zshrc"
        if zshrc.exists():
            try:
                result = subprocess.run(
                    ["bash", "-c", f"source {zshrc} 2>/dev/null && echo \"${{IB_USER}}\" && echo \"${{IB_PASS}}\""],
                    capture_output=True, text=True, timeout=10
                )
                lines = result.stdout.strip().split("\n")
                if len(lines) >= 2 and lines[0] and lines[1]:
                    user, pw = lines[0], lines[1]
                    os.environ["IB_USER"] = user
                    os.environ["IB_PASS"] = pw
            except Exception:
                pass
    if not user or not pw:
        logger.error("IB_USER and IB_PASS must be set in environment")
        logger.error("Add to ~/.zshrc: export IB_USER='...' && export IB_PASS='...'")
        sys.exit(1)
    return user, pw


# ── config.ini generation ───────────────────────────────────────────────────

##
# Generate config.ini in the IBC config directory.
#
# @param paper: If True, write TradingMode=paper; otherwise live.
# @return: Path to the generated config.ini file.
def generate_config_ini(paper: bool = True) -> Path:
    IBC_CONF_DIR.mkdir(parents=True, exist_ok=True)
    user, pw = get_credentials()

    trading_mode = "paper" if paper else "live"

    ini_content = textwrap.dedent(f"""\
    # Auto-generated by ibgateway.py - DO NOT EDIT MANUALLY
    [IBC]
    FIX=no

    # Authentication
    IbLoginId={user}
    IbPassword={pw}

    # Trading Mode
    TradingMode={trading_mode}

    # Second Factor Authentication
    ReloginAfterSecondFactorAuthenticationTimeout=yes
    SecondFactorAuthenticationExitInterval=120
    SecondFactorAuthenticationTimeout=180

    # Startup
    MinimizeMainWindow=yes

    # Connection handling
    ExistingSessionDetectedAction=primary
    AcceptIncomingConnectionAction=accept
    AcceptNonBrokerageAccountWarning=yes
    ReadOnlyLogin=yes

    # API port
    OverrideTwsApiPort={IB_GW_PORT}

    # Closedown
    IbAutoClosedown=no
    AutoLogoffTime=
    AutoRestartTime=
    ClosedownAt=

    # Misc
    AllowBlindTrading=no

    # Command server
    CommandServerPort={IBC_CMD_PORT}
    ControlFrom=
    BindAddress=
    CommandPrompt=
    SuppressInfoMessages=yes

    # Diagnostics
    LogStructureWhen=open
    IncludeStackTraceForExceptions=no
    """)

    ini_path = IBC_CONF_DIR / "config.ini"
    ini_path.write_text(ini_content)
    logger.info("Config written: %s", ini_path)
    return ini_path


# ── Gateway lifecycle ───────────────────────────────────────────────────────

##
# Start IB Gateway via IBC and block until the Gateway process exits.
#
# Starts ONLY the gateway (QuestDB is orchestrated by SessionManager).
# Reads credentials, generates config.ini, launches displaybannerandlaunch.sh,
# and writes PID files.
def start_gateway():
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

    user, pw = get_credentials()
    ini_path = generate_config_ini(paper=True)

    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    display_script = SCRIPTS_DIR / "displaybannerandlaunch.sh"
    if not display_script.exists():
        logger.error("%s not found. Run 'python3 -m ibgateway install_scripts' first.",
                     display_script)
        sys.exit(1)

    env = os.environ.copy()
    env.update({
        "TWS_MAJOR_VRSN": TWS_MAJOR_VRSN,
        "IBC_INI": str(ini_path),
        "TRADING_MODE": "paper",
        "TWOFA_TIMEOUT_ACTION": "exit",
        "IBC_PATH": IBC_PATH,
        "TWS_PATH": TWS_PATH,
        "TWS_SETTINGS_PATH": TWS_SETTINGS_PATH,
        "LOG_PATH": str(LOGS_DIR),
        "APP": "GATEWAY",
        "TWSUSERID": user,
        "TWSPASSWORD": pw,
        "JAVA_PATH": JAVA_HOME_25 + "/bin",
    })

    logger.info("Starting IB Gateway...")
    logger.info("  Display script: %s", display_script)
    logger.info("  Config: %s", ini_path)

    proc = subprocess.Popen(
        ["/bin/bash", str(display_script)],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    pid_file = LOGS_DIR / "gateway.pid"
    pid_file.write_text(str(proc.pid))
    gw_pid_file = CONFIGS_DIR / ".ibkr_gateway.pid"
    CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    gw_pid_file.write_text(str(os.getpid()) + "\n")

    logger.info("Gateway subprocess started (PID %d), waiting for exit...", proc.pid)
    try:
        proc.wait()
    finally:
        logger.info("Gateway subprocess terminated.")
        if pid_file.exists():
            pid_file.unlink()
        try:
            gw_pid_file.unlink()
        except FileNotFoundError:
            pass


##
# Poll IB Gateway port 4002 until the API is ready.
#
# @param timeout: Maximum seconds to wait.
# @return: True if the API became ready within the timeout, False otherwise.
def wait_for_api(timeout: int = 120) -> bool:
    from session_manager import SessionManager
    deadline = time.time() + timeout
    attempt = 0

    while time.time() < deadline:
        attempt += 1
        mgr = SessionManager()
        try:
            ib = mgr.get_ib_conn()
            if ib is not None:
                logger.info("API ready on attempt %d.", attempt)
                mgr._force_disconnect_ib(ib)
                return True
        except Exception:
            pass

        if attempt == 1:
            logger.info("Waiting for API (attempt %d)...", attempt)
        time.sleep(2)

    logger.error("API not ready after %ds timeout", timeout)
    return False


##
# Gracefully stop IB Gateway with kill fallback.
#
# Sends STOP to IBC, runs commandsend.sh, SIGTERM/SIGKILL remaining Java
# processes.  Does NOT stop QuestDB — SessionManager orchestrates that.
def stop_gateway():
    logger.info("Stopping Gateway...")

    _send_stop_via_nc()

    cmd_send = SCRIPTS_DIR / "commandsend.sh"
    if cmd_send.exists():
        try:
            subprocess.run(
                [str(cmd_send), "STOP"],
                timeout=10,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except Exception as e:
            logger.warning("commandsend.sh warning: %s", e)

    time.sleep(5)

    _kill_java_processes("ibgateway", "IBC")
    _kill_java_processes("IBC")

    logger.info("Gateway and services stopped.")


##
# Send STOP + EXIT commands to the IBC command server via raw socket.
def _send_stop_via_nc():
    try:
        s = socket.create_connection(("127.0.0.1", IBC_CMD_PORT), timeout=3)
        s.sendall(b"STOP\r\n")
        time.sleep(0.5)
        s.sendall(b"EXIT\r\n")
        s.close()
        logger.info("  STOP sent via socket.")
    except Exception as e:
        logger.info("  Socket STOP failed (normal if Gateway not running): %s", e)


##
# Kill all Java processes matching any of the given pgrep patterns.
#
# Sends SIGTERM first, waits 3 seconds, then sends SIGKILL to any
# remaining matches.
#
# @param *patterns: One or more pgrep -f patterns to match.
def _kill_java_processes(*patterns: str):
    for pat in patterns:
        try:
            result = subprocess.run(
                ["pgrep", "-f", pat],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode != 0:
                continue
            pids = [int(p) for p in result.stdout.strip().split()]
            for pid in pids:
                logger.info("  Sending SIGTERM to PID %d (%s)...", pid, pat)
                try:
                    os.kill(pid, signal.SIGTERM)
                except ProcessLookupError:
                    pass
        except Exception:
            pass

    time.sleep(3)
    for pat in patterns:
        try:
            result = subprocess.run(
                ["pgrep", "-f", pat],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode != 0:
                continue
            pids = [int(p) for p in result.stdout.strip().split()]
            for pid in pids:
                logger.info("  Sending SIGKILL to PID %d (%s)...", pid, pat)
                try:
                    os.kill(pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
        except Exception:
            pass


# ── Status ──────────────────────────────────────────────────────────────────

##
# Return a dict summarising the gateway and questdb component statuses.
#
# @return: A dict with keys questdb, gateway, and keepalive (False placeholder).
def gateway_status() -> Dict:
    status = {
        "questdb": {"running": False, "port": QUESTDB_PORT, "pid": None},
        "gateway": {"running": False, "port": IB_GW_PORT, "pid": None},
        "keepalive": False,
    }

    qpid = QuestDBManager.find_questdb_pid()
    if qpid:
        status["questdb"]["running"] = True
        status["questdb"]["pid"] = qpid

    status["gateway"]["running"] = QuestDBManager.is_port_open("127.0.0.1", IB_GW_PORT, timeout=1.0)

    try:
        result = subprocess.run(
            ["pgrep", "-f", "displaybannerandlaunch"],
            capture_output=True, text=True, timeout=3,
        )
        if result.returncode == 0 and result.stdout.strip():
            status["gateway"]["pid"] = int(result.stdout.strip().split()[0])
    except Exception:
        pass

    return status


# ── Ensure gateway is ready ─────────────────────────────────────────────────

##
# Idempotent: return True if the API is ready, otherwise start the Gateway.
#
# @param timeout: Maximum seconds to wait for the API.
# @return: True if the Gateway API is ready, False otherwise.
def ensure_gateway(timeout: int = 120) -> bool:
    from session_manager import SessionManager
    from session_manager import IBConnectionFatalError

    if QuestDBManager.is_port_open("127.0.0.1", IB_GW_PORT, timeout=1.0):
        mgr = SessionManager()
        try:
            ib = mgr.get_ib_conn()
            if ib is not None:
                mgr._force_disconnect_ib(ib)
                return True
        except IBConnectionFatalError:
            pass
        except Exception:
            pass

        logger.debug("Gateway port open but API not responding; restarting...")
        stop_gateway()
        time.sleep(3)

    import threading
    gw_thread = threading.Thread(target=start_gateway, daemon=True)
    gw_thread.start()

    if wait_for_api(timeout=timeout):
        logger.info("Gateway is ready.")
        return True
    else:
        logger.error("Gateway failed to become ready")
        return False


# ── Script installation ─────────────────────────────────────────────────────

##
# Copy IBC scripts from ~/Applications/IBC into the project scripts directory.
#
# Creates executable copies of displaybannerandlaunch.sh, ibcstart.sh, stop.sh,
# commandsend.sh, and version.  Missing source scripts are replaced with stub
# placeholders.
def install_scripts():
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

    mappings = [
        ("displaybannerandlaunch.sh", "scripts/displaybannerandlaunch.sh"),
        ("ibcstart.sh", "scripts/ibcstart.sh"),
        ("stop.sh", "scripts/stop.sh"),
        ("commandsend.sh", "scripts/commandsend.sh"),
        ("version", "scripts/version"),
    ]

    ibc_root = Path.home() / "Applications" / "IBC"

    for src_name, dest_rel in mappings:
        src = ibc_root / src_name
        if src_name == "scripts/displaybannerandlaunch.sh":
            src = ibc_root / "scripts" / "displaybannerandlaunch.sh"
        elif src_name == "scripts/ibcstart.sh":
            src = ibc_root / "scripts" / "ibcstart.sh"
        dest = PROJECT_DIR / dest_rel

        if src.exists():
            shutil.copy2(str(src), str(dest))
            dest.chmod(dest.stat().st_mode | 0o111)
            logger.info("  Copied %s -> %s", src, dest)
        else:
            logger.warning("  %s not found, skipping", src)
            dest.write_text("#!/bin/bash\necho 'Placeholder: install real script at " + str(src) + "'\n")
            dest.chmod(0o755)

    logger.info("Scripts installed.")
