#!/bin/bash
# IB TWS + IBC Launcher - 24/7 Headless Operation (Paper Trading)
# Reads credentials from environment variables: IB_USER, IB_PASS
# Generates config.ini on-the-fly with credentials, cleans up on exit.
# Uses IBC (https://github.com/IbcAlpha/IBC) - actively maintained automation

set -uo pipefail

# --- Configuration ---
TWS_MAJOR_VRSN=10.45
IBC_PATH="${HOME}/Applications/IBC"
TWS_PATH="${HOME}/Applications"
IB_APP="GATEWAY"
TWS_SETTINGS_PATH="${HOME}/Jts"
LOG_PATH="${IBC_PATH}/logs"
CONF_DIR="${IBC_PATH}/conf"

# Source ~/.zshrc if env vars aren't set (launchd doesn't load shell rc)
if [[ -z "${IB_USER:-}" || -z "${IB_PASS:-}" ]]; then
  if [[ -f "${HOME}/.zshrc" ]]; then
    set +e
    source "${HOME}/.zshrc" 2>/dev/null
    set -e
  fi
fi

IB_USER="${IB_USER:-}"
IB_PASS="${IB_PASS:-}"
TRADING_MODE="${TRADING_MODE:-paper}"

# Validate
if [[ -z "$IB_USER" || -z "$IB_PASS" ]]; then
  echo "ERROR: IB_USER and IB_PASS environment variables must be set." >&2
  echo "Add to ~/.zshrc:" >&2
  echo '  export IB_USER="your_ibkr_username"' >&2
  echo '  export IB_PASS="your_ibkr_password"' >&2
  exit 1
fi

mkdir -p "$CONF_DIR" "$LOG_PATH"

CLEANUP_FILES=()

cleanup() {
  echo "Cleaning up config files..."
  for f in "${CLEANUP_FILES[@]}"; do
    if [[ -f "$f" ]]; then
      rm -f "$f"
      echo "  Removed: $f"
    fi
  done
}
trap cleanup EXIT INT TERM

# --- Generate config.ini ---
INI_FILE="${CONF_DIR}/config.ini"
CLEANUP_FILES+=("$INI_FILE")

cat > "$INI_FILE" <<INIEOF
# Auto-generated by ibkr-start.sh - DO NOT EDIT MANUALLY
[IBC]
FIX=no

# Authentication
IbLoginId=${IB_USER}
IbPassword=${IB_PASS}

# Trading Mode - paper doesn't require 2FA
TradingMode=${TRADING_MODE}

# Second Factor Authentication
ReloginAfterSecondFactorAuthenticationTimeout=yes
SecondFactorAuthenticationExitInterval=120
SecondFactorAuthenticationTimeout=180

# Startup - minimize TWS window
MinimizeMainWindow=yes

# Connection handling
ExistingSessionDetectedAction=primary
AcceptIncomingConnectionAction=accept
AcceptNonBrokerageAccountWarning=yes
# ReadOnlyLogin=yes skips 2FA (work with TWS paper accounts)
ReadOnlyLogin=yes

# API port - use 4002 for Gateway paper
OverrideTwsApiPort=4002

# Closedown - never auto-close (24/7 operation)
IbAutoClosedown=no
AutoLogoffTime=
AutoRestartTime=
ClosedownAt=

# Misc
AllowBlindTrading=no

# Command server
CommandServerPort=7462
ControlFrom=
BindAddress=
CommandPrompt=
SuppressInfoMessages=yes

# Diagnostics
LogStructureWhen=open
IncludeStackTraceForExceptions=no
INIEOF

chmod 600 "$INI_FILE"
echo "Generated: $INI_FILE"

# --- Generate IBControllerStart.ini (needed for TWS) ---
START_INI="${CONF_DIR}/IBControllerStart.ini"
CLEANUP_FILES+=("$START_INI")

cat > "$START_INI" <<STARTINI
# Auto-generated by ibkr-start.sh
TradingMode=${TRADING_MODE}
IbAutoClosedown=no
ClosedownAt=
STARTINI

chmod 600 "$START_INI"
echo "Generated: $START_INI"

# --- Launch ---
echo "Starting ${IB_APP} ${TWS_MAJOR_VRSN} via IBC..."
echo "  User: ${IB_USER}"
echo "  Mode: ${TRADING_MODE}"
echo "  Logs: ${LOG_PATH}"

export TWS_MAJOR_VRSN
export IBC_INI="$INI_FILE"
export TRADING_MODE
export TWOFA_TIMEOUT_ACTION=exit
export IBC_PATH
export TWS_PATH
export TWS_SETTINGS_PATH
export LOG_PATH
export APP=${IB_APP}

# Pass credentials via env vars
# Use config.ini for credentials, not env vars
unset TWSUSERID TWSPASSWORD FIXUSERID FIXPASSWORD

# --- Start QuestDB (time-series DB) ---
QUESTDB_HOME="${HOME}/apps/questdb-9.4.3"
JAVA_HOME_25="/usr/local/Cellar/openjdk@25/25.0.3"

if ! pgrep -f "questdb.*ServerMain" >/dev/null 2>&1; then
  echo "Starting QuestDB..."
  JAVA_HOME="${JAVA_HOME_25}" "${QUESTDB_HOME}/questdb.sh" start -d "${HOME}/.questdb" >/dev/null 2>&1
  echo "  QuestDB started (port 9000)"
else
  echo "QuestDB already running."
fi

cd "${IBC_PATH}"
exec "${HOME}/.local/bin/ibkr-tws-launch.sh" -inline
